### ISSUE TITLE
Add doctest's upstream tests.

### ISSUE THREAD

**Issue by Klaim** [build2-packaging/doctest#1]
(Congrats on you your first package! ;) )

The main improvement this package could have would be to also add the targets for the tests that are in the original package. 

It's not super critical though, in particular for this library.

That's it. :)

**Comment by lyrahgames** [comment]
(Thank you very much. I was a little bit afraid of it ;) )

I have already thought about this myself.
The problem is that for including the tests one will have to manually adapt the tests, so that build2 will be able to run them via a few testscipts.
I am not very experienced with these testscripts, yet.
And therefore the main goal was to first test the packaging system.
But of course, you are right and I will add this functionality as soon as possible.

**Comment by Klaim** [comment]
Yes indeed it's not an easy process. It's the hardest part in my experience doing so because you have to understand the library in question and how it is built and tested before being able to write the same in build2.

However don't feel pressured to absolutely do this immediately: I created this issue so that it is visible to anyone wanting to help and as a todolist for you if you want to and have time to continue improving this package.

I don't think I will have much time to help as the same process is ongoing on several packaging I'm preparing to move here, though once that's done I'll take a look if you didn't already.
